# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nelmo', '0002_remove_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
