# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nelmo', '0005_auto_20200606_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
